### ISSUE TITLE
Macroalgae displays and nitpicky color requests

### ISSUE THREAD

**Issue by sscolaro** [tbep-tech/piney-point#5]
Instead of displaying Macroalgae by genus, display by group (red, green or brown). In the field, it is often challenging to delineate percentage of the different drift red algae and are therefore recorded as "Mixed Red" or by the dominant algae type. Change chart colors to reflect algal group color.

**Comment by fawda123** [comment]
@sscolaro done
![image](https://user-images.githubusercontent.com/3086881/118268979-1c690d80-b48c-11eb-9966-05c6049d0804.png)
